name: Deploy main

on:
  push:
    tags:
      - '*'

permissions:
  contents: read

jobs:
  assemble-and-publish:
    uses: ministryofjustice/laa-ccms-common-workflows/.github/workflows/gradle-build-and-publish.yml@v1
    permissions:
      contents: write
      packages: write
    with:
      build_command: 'assemble'
      publish_package: 'true'
      junit_results: 'false'
      junit_report: 'false'
      checkstyle_report: 'false'
      jacoco_coverage_report: 'false'
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}

  ecr-publish-image:
    needs: [ assemble-and-publish ]
    uses: ministryofjustice/laa-ccms-common-workflows/.github/workflows/ecr-publish-image.yml@v1
    permissions:
      contents: read
      id-token: write
    with:
      image_version: ${{ format('{0}-{1}', vars.IMAGE_PREFIX, needs.assemble-and-publish.outputs.published_artifact_version) }}
      jar_subproject: 'dstew-access-service'
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
      ecr_repository: ${{ vars.ECR_REPOSITORY }}
      ecr_region: ${{ vars.ECR_REGION }}
      ecr_role_to_assume: ${{ secrets.ECR_ROLE_TO_ASSUME }}

  update-helm-chart:
    needs: [ ecr-publish-image ]
    uses: ministryofjustice/laa-ccms-common-workflows/.github/workflows/update-helm-chart.yml@v1
    with:
      helm_charts_repository: 'laa-data-stewardship-helm-charts'
      helm_charts_branch: 'main' # no 'development' branch
      service_name: 'laa-data-stewardship-shared'
      subchart_name: 'laa-data-stewardship-access'
      application_version: ${{ needs.ecr-publish-image.outputs.published_image_version }}
      github_bot_username: 'laa-data-stewardship'
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
      github_app_id: ${{ secrets.GITHUBAPP_ID }}
      github_app_private_key: ${{ secrets.GITHUBAPP_PRIVATE_KEY }}
      github_app_organisation: 'ministryofjustice'