name: Feature build and test
on: [push]

jobs:
  feature_branch:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Setup Containers
        run: docker compose up -d

      - name: Build jar and run tests
        uses: ./.github/actions/build-and-test
        with:
          user: ${{ github.actor }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Snyk Scan
        uses: ./.github/actions/synk-scan
        with:
          token: ${{ secrets.SNYK_TOKEN }}

#      - name: Create Docker image
#        uses: ./.github/actions/publish
#        with:
#          registry: ${{ inputs.environment }}
#          repository: ${{ inputs.dockerfile_path }}
#          tag: ${{ inputs.image_tag }}

      - name: Post Setup Containers
        run: docker compose down